In [1]:
import numpy as np
import pandas as pd

from joblib import dump, load

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import PolynomialFeatures
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

import scipy.stats as stats

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 50)

In [9]:
df_laptops_train = pd.read_csv('./data/df_laptops_train_output1.csv', sep=',', encoding='utf-8')
df_laptops_unlabeled = pd.read_csv('./data/df_laptops_test_unlabeled_output1.csv', sep=',', encoding='utf-8')

In [10]:
# resumen estadistico de variable price
df_laptops_train.describe()

,id,Ram,Weight,Price,TouchScreen,Ips,Ppi,HDD,SSD
count,1166.000000,1166.000000,1166.000000,1166.000000,1166.000000,1166.000000,1166.000000,1166.000000,1166.000000
mean,636.512007,8.507719,2.050686,12.385126,0.143225,0.283019,146.607787,414.802744,187.989708
std,366.205183,5.136040,0.674661,24.476793,0.350452,0.450659,42.705848,517.624081,187.302367
min,0.000000,2.000000,0.690000,9.134616,0.000000,0.000000,90.583402,0.000000,0.000000
25%,320.250000,4.000000,1.500000,10.402328,0.000000,0.000000,127.335675,0.000000,0.000000
50%,633.500000,8.000000,2.040000,10.882316,0.000000,0.000000,141.211998,0.000000,256.000000
75%,950.500000,8.000000,2.310000,11.288115,0.000000,1.000000,157.350512,1000.000000,256.000000
max,1272.000000,64.000000,4.700000,499.766079,1.000000,1.000000,352.465147,2000.000000,1024.000000

In [12]:
# Resumen estadistico unlabeled
df_laptops_unlabeled.describe()

,id,Ram,Weight,TouchScreen,Ips,Ppi,HDD,SSD,CalculatedPrice
count,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,63.000000,0.0
mean,580.539683,8.507937,2.002857,0.190476,0.238095,154.883423,500.000000,164.190476,NaN
std,385.209278,5.423584,0.618170,0.395831,0.429339,51.980062,575.017531,184.184240,NaN
min,23.000000,2.000000,0.690000,0.000000,0.000000,90.583402,0.000000,0.000000,NaN
25%,236.500000,4.000000,1.550000,0.000000,0.000000,127.335675,0.000000,0.000000,NaN
50%,568.000000,8.000000,2.020000,0.000000,0.000000,141.211998,0.000000,128.000000,NaN
75%,948.000000,8.000000,2.265000,0.000000,0.000000,161.491315,1000.000000,256.000000,NaN
max,1271.000000,32.000000,4.300000,1.000000,1.000000,316.965060,2000.000000,1000.000000,NaN

In [13]:
# Tipos de datos
df_laptops_train.dtypes

id               int64
Company         object
TypeName        object
Ram              int64
Weight         float64
Price          float64
TouchScreen      int64
Ips              int64
Ppi            float64
Cpu_brand       object
HDD            float64
SSD              int64
Gpu_brand       object
Os              object
dtype: object

In [15]:
# Valores unicos en columnas categóricas
featuresCategoricas = ['Company', 'TypeName', 'TouchScreen', 'Ips', 'Cpu_brand', 'Gpu_brand', 'Os']

# verificar valores unicos en cada variable categorica
for feature in featuresCategoricas:
    print(f'{feature}: {df_laptops_train[feature].unique()}')

Company: ['Lenovo' 'Dell' 'HP' 'Asus' 'Toshiba' 'Acer' 'MSI' 'Razer' 'Samsung'
 'Chuwi' 'Microsoft' 'Mediacom' 'LG' 'Vero' 'Apple' 'Huawei' 'Xiaomi'
 'Fujitsu' 'Google']
TypeName: ['Notebook' 'Ultrabook' '2 in 1 Convertible' 'Gaming' 'Netbook'
 'Workstation']
TouchScreen: [0 1]
Ips: [0 1]
Cpu_brand: ['Intel Core i3' 'Intel Core i5' 'Intel Core i7' 'AMD Processor'
 'Other Intel Processor']
Gpu_brand: ['Intel' 'Nvidia' 'AMD']
Os: ['Others' 'Windows' 'Mac']

Todas las verificaciones están correctas, ergo, los datos están limpios c: